import type { Config } from "@react-router/dev/config";

export default {
  ssr: false,
  prerender: [
    "/en",
    "/en/sign-up",
    "/en/sign-in",
    "/sk",
    "/sk/prihlasit-sa",
    "/sk/registracia",
    "/cz",
    "/cz/prihlaseni",
    "/cz/registrace",
    "/de",
    "/de/anmelden",
    "/de/registrieren",
    "/es",
    "/es/acceder",
    "/es/registrarse",
    "/fr",
    "/fr/kirjaudu-sisaan",
    "/fr/rekisteroidy",
    "/it",
    "/it/accedi",
    "/it/registrati",
    "/pl",
    "/pl/zaloguj-sie",
    "/pl/zarejestruj-sie",
    "/nl",
    "/nl/aanmelden",
    "/nl/registreren",
    "/si",
    "/si/prijava",
    "/si/registracija",
    "/fi",
    "/fi/kirjaudu-sisaan",
    "/fi/rekisteroidy",
    "/se",
    "/se/logga-in",
    "/se/registrera",
    "/no",
    "/no/logg-inn",
    "/no/registrer",
    "/dk",
    "/dk/log ind",
    "/dk/registrer",
    "/hu",
    "/hu/bejelentkezes",
    "/hu/regisztracio",
  ]
} satisfies Config;
