services:
  mysql_notification_service:
      container_name: zdielaj_si_db_notification_service
      image: mysql
      env_file:
        - ./.env.notification
      ports:
        - 3309:3306
      volumes:
        - 'mysql_notification_service_data:/data/db'

  dynamodb-zdielajsi:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-zdielajsi
    ports:
      - 8000:8000
    restart: always
    volumes:
      - './data:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  dynamodb-zdielajsi-admin: 
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-zdielajsi-admin
    depends_on:
      - dynamodb-zdielajsi
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-zdielajsi:8000
      - AWS_REGION=local

  core:
    image: node:22-alpine
    working_dir: /home/node
    command: sh -c "corepack enable && yarn set version berry && yarn install && yarn start"
    depends_on:
      - dynamodb-zdielajsi
    restart: unless-stopped
    ports:
      - 3010:3010
    env_file:
      - ./backend/.env.local
    volumes:
      - "./backend:/home/node"

  frontend:
    image: node:22-alpine
    working_dir: /home/node
    command: sh -c "corepack enable && yarn set version berry && yarn install && yarn start"
    restart: unless-stopped
    volumes:
      - "./frontend:/home/node"
    ports:
      - 3000:3000

  user_service:
    image: juffalow/user-service:latest
    restart: unless-stopped
    env_file:
      - ./.env.user
    ports:
      - 3013:3010

  upload_service:
    image: openservicesdev/aws-upload-service:latest
    depends_on:
      - dynamodb-zdielajsi
    restart: unless-stopped
    env_file:
      - ./.env.upload
    ports:
      - 3014:3010

  upload_service_worker:
    image: openservicesdev/aws-upload-service:latest
    command: sh -c "node ./dist/worker.js"
    depends_on:
      - dynamodb-zdielajsi
    restart: unless-stopped
    env_file:
      - ./.env.upload

  notification_service:
    image: juffalow/notification-service:latest
    depends_on:
      - mysql_notification_service
    restart: unless-stopped
    env_file:
      - ./.env.notification
    ports:
      - 3015:3010

  notification_service_worker:
    image: juffalow/notification-service:latest
    working_dir: /home/juffuser/notification-service
    command: sh -c "node ./dist/worker.js"
    depends_on:
      - mysql_notification_service
    restart: unless-stopped
    env_file:
      - ./.env.notification

volumes:
  mysql_notification_service_data:
