services:
  mysql_core:
      container_name: zdielaj_si_db_core
      image: mysql
      environment:
        - MYSQL_DATABASE=zdielajsi_core
        - MYSQL_USER=zdielajsi_core
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_PORT=3306
      ports:
        - 3306:3306
      volumes:
        - 'mysql_core_data:/data/db'

  mysql_user_service:
      container_name: zdielaj_si_db_user_service
      image: mysql
      env_file:
        - ./.env.user
      ports:
        - 3307:3306
      volumes:
        - 'mysql_user_service_data:/data/db'

  mysql_upload_service:
      container_name: zdielaj_si_db_upload_service
      image: mysql
      env_file:
        - ./.env.upload
      ports:
        - 3308:3306
      volumes:
        - 'mysql_upload_service_data:/data/db'

  mysql_notification_service:
      container_name: zdielaj_si_db_notification_service
      image: mysql
      env_file:
        - ./.env.notification
      ports:
        - 3309:3306
      volumes:
        - 'mysql_notification_service_data:/data/db'

  core:
    image: node:20-alpine
    working_dir: /home/node
    command: sh -c "yarn install && yarn start"
    depends_on:
      - mysql_core
    restart: unless-stopped
    ports:
      - 3010:3010
    environment:
      - DATABASE_HOST=mysql_core
      - DATABASE_NAME=zdielajsi_core
      - DATABASE_USER=zdielajsi_core
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
    links:
      - mysql_core
    volumes:
      - "./backend:/home/node"

  frontend:
    image: node:20-alpine
    working_dir: /home/node
    command: sh -c "yarn install && yarn start"
    restart: unless-stopped
    volumes:
      - "./frontend:/home/node"
    ports:
      - 3000:3000

  user_service:
    image: juffalow/user-service:latest
    depends_on:
      - mysql_user_service
    restart: unless-stopped
    env_file:
      - ./.env.user
    ports:
      - 3013:3010
    links:
      - mysql_user_service

  upload_service:
    image: juffalow/upload-service:latest
    depends_on:
      - mysql_upload_service
    restart: unless-stopped
    env_file:
      - ./.env.upload
    ports:
      - 3014:3010
    links:
      - mysql_upload_service

  upload_service_worker:
    image: juffalow/upload-service:latest
    working_dir: /home/juffuser/upload-service
    command: sh -c "node ./dist/worker.js"
    depends_on:
      - mysql_upload_service
    restart: unless-stopped
    env_file:
      - ./.env.upload
    links:
      - mysql_upload_service

  notification_service:
    image: juffalow/notification-service:latest
    depends_on:
      - mysql_notification_service
    restart: unless-stopped
    env_file:
      - ./.env.notification
    ports:
      - 3015:3010
    links:
      - mysql_notification_service

  notification_service_worker:
    image: juffalow/notification-service:latest
    working_dir: /home/juffuser/notification-service
    command: sh -c "node ./dist/worker.js"
    depends_on:
      - mysql_notification_service
    restart: unless-stopped
    env_file:
      - ./.env.notification
    links:
      - mysql_notification_service

volumes:
  mysql_core_data:
  mysql_user_service_data:
  mysql_upload_service_data:
  mysql_notification_service_data:
