export const ROUTES = {
  en: {
    prefix: 'en/',
    home: '',
    signIn: 'sign-in',
    signUp: 'sign-up',
    albums: 'albums',
    album: 'album/:id',
    profile: 'profile',
    publicProfile: 'profile/:id',
    privacyPolicy: 'privacy-policy',
    subscription: 'subscription',
  },
  sk: {
    prefix: 'sk/',
    home: '',
    signIn: 'prihlasit-sa',
    signUp: 'registracia',
    albums: 'albumy',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'zasady-ochrany-osobnych-udajov',
    subscription: 'predplatne',
  },
  cz: {
    prefix: 'cz/',
    home: '',
    signIn: 'prihlaseni',
    signUp: 'registrace',
    albums: 'alba',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'zasady-ochrany-osobnich-udaju',
    subscription: 'predplatne',
  },
  de: {
    prefix: 'de/',
    home: '',
    signIn: 'anmelden',
    signUp: 'registrieren',
    albums: 'alben',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'datenschutz',
    subscription: 'abonnement',
  },
  es: {
    prefix: 'es/',
    home: '',
    signIn: 'acceder',
    signUp: 'registrarse',
    albums: 'albumes',
    album: 'album/:id',
    profile: 'perfil',
    publicProfile: 'perfil/:id',
    privacyPolicy: 'politica-de-privacidad',
    subscription: 'suscripcion',
  },
  fr: {
    prefix: 'fr/',
    home: '',
    signIn: 'se-connecter',
    signUp: 'inscription',
    albums: 'albums',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'politique-de-confidentialite',
    subscription: 'abonnement',
  },
  it: {
    prefix: 'it/',
    home: '',
    signIn: 'accedi',
    signUp: 'registrati',
    albums: 'album',
    album: 'album/:id',
    profile: 'profilo',
    publicProfile: 'profilo/:id',
    privacyPolicy: 'politica-di-privacy',
    subscription: 'abbonamento',
  },
  pl: {
    prefix: 'pl/',
    home: '',
    signIn: 'zaloguj-sie',
    signUp: 'zarejestruj-sie',
    albums: 'albumy',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'prawilnik-o-zasebnosti',
    subscription: 'subskrypcja',
  },
  nl: {
    prefix: 'nl/',
    home: '',
    signIn: 'aanmelden',
    signUp: 'registreren',
    albums: 'album',
    album: 'album/:id',
    profile: 'profiel',
    publicProfile: 'profiel/:id',
    privacyPolicy: 'privacy-policy',
    subscription: 'abonnement',
  },
  si: {
    prefix: 'si/',
    home: '',
    signIn: 'prijava',
    signUp: 'registracija',
    albums: 'albumi',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'pravilnik-o-zasebnosti',
    subscription: 'prenumerata',
  },
  fi: {
    prefix: 'fi/',
    home: '',
    signIn: 'kirjaudu-sisaan',
    signUp: 'rekisteroidy',
    albums: 'albumit',
    album: 'albumi/:id',
    profile: 'profiili',
    publicProfile: 'profiili/:id',
    privacyPolicy: 'tietosuojakaytannos',
    subscription: 'tilaus',
  },
  se: {
    prefix: 'se/',
    home: '',
    signIn: 'logga-in',
    signUp: 'registrera',
    albums: 'album',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'integritetspolicy',
    subscription: 'prenumeration',
  },
  no: {
    prefix: 'no/',
    home: '',
    signIn: 'logg-inn',
    signUp: 'registrer',
    albums: 'album',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'personvern',
    subscription: 'abonnement',
  },
  dk: {
    prefix: 'dk/',
    home: '',
    signIn: 'log ind',
    signUp: 'registrer',
    albums: 'album',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'personvern',
    subscription: 'abonnement',
  },
  hu: {
    prefix: 'hu/',
    home: '',
    signIn: 'bejelentkezes',
    signUp: 'regisztracio',
    albums: 'albumok',
    album: 'album/:id',
    profile: 'profil',
    publicProfile: 'profil/:id',
    privacyPolicy: 'adatvedelmi-szabalyzat',
    subscription: 'elofizetes',
  },
};
