import { type RouteConfig, index, route, prefix } from '@react-router/dev/routes';
import { ROUTES } from './constants';

export default [
  index('./routes/index.tsx'),
  ...prefix(ROUTES.en.prefix, [
    index('routes/home.tsx', { id: 'en-home-index' }),
    route(ROUTES.en.signIn, 'routes/signIn.tsx', { id: 'en-sign-in' }),
    route(ROUTES.en.signUp, 'routes/signUp.tsx', { id: 'en-sign-up' }),
    route(ROUTES.en.albums, 'routes/albums.tsx', { id: 'en-albums' }),
    route(ROUTES.en.album, 'routes/album.tsx', { id: 'en-album' }),
    route(ROUTES.en.publicProfile, 'routes/publicProfile.tsx', { id: 'en-public-profile' }),
    route(ROUTES.en.profile, 'routes/profile.tsx', { id: 'en-profile' }),
    route(ROUTES.en.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'en-privacy-policy' }),
  ]),
  ...prefix(ROUTES.sk.prefix, [
    index('routes/home.tsx', { id: 'sk-home-index' }),
    route('prihlasit-sa', 'routes/signIn.tsx', { id: 'sk-sign-in' }),
    route('registracia', 'routes/signUp.tsx', { id: 'sk-sign-up' }),
    route('albumy', 'routes/albums.tsx', { id: 'sk-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'sk-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'sk-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'sk-profile' }),
    route(ROUTES.sk.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'sk-privacy-policy' }),
  ]),
  ...prefix(ROUTES.cz.prefix, [
    index('routes/home.tsx', { id: 'cz-home-index' }),
    route('prihlaseni', 'routes/signIn.tsx', { id: 'cz-sign-in' }),
    route('registrace', 'routes/signUp.tsx', { id: 'cz-sign-up' }),
    route('alba', 'routes/albums.tsx', { id: 'cz-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'cz-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'cz-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'cz-profile' }),
    route(ROUTES.cz.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'cz-privacy-policy' }),
  ]),
  ...prefix(ROUTES.de.prefix, [
    index('routes/home.tsx', { id: 'de-home-index' }),
    route('anmelden', 'routes/signIn.tsx', { id: 'de-sign-in' }),
    route('registrieren', 'routes/signUp.tsx', { id: 'de-sign-up' }),
    route('alben', 'routes/albums.tsx', { id: 'de-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'de-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'de-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'de-profile' }),
    route(ROUTES.de.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'de-privacy-policy' }),
  ]),
  ...prefix(ROUTES.es.prefix, [
    index('routes/home.tsx', { id: 'es-home-index' }),
    route('acceder', 'routes/signIn.tsx', { id: 'es-sign-in' }),
    route('registrarse', 'routes/signUp.tsx', { id: 'es-sign-up' }),
    route('albumes', 'routes/albums.tsx', { id: 'es-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'es-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'es-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'es-profile' }),
    route(ROUTES.es.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'es-privacy-policy' }),
  ]),
  ...prefix(ROUTES.fr.prefix, [
    index('routes/home.tsx', { id: 'fr-home-index' }),
    route('kirjaudu-sisaan', 'routes/signIn.tsx', { id: 'fr-sign-in' }),
    route('rekisteroidy', 'routes/signUp.tsx', { id: 'fr-sign-up' }),
    route('albumit', 'routes/albums.tsx', { id: 'fr-albums' }),
    route('albumi/:id', 'routes/album.tsx', { id: 'fr-album' }),
    route('profiili/:id', 'routes/publicProfile.tsx', { id: 'fr-public-profile' }),
    route('profiili', 'routes/profile.tsx', { id: 'fr-profile' }),
    route(ROUTES.fr.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'fr-privacy-policy' }),
  ]),
  ...prefix(ROUTES.it.prefix, [
    index('routes/home.tsx', { id: 'it-home-index' }),
    route('accedi', 'routes/signIn.tsx', { id: 'it-sign-in' }),
    route('registrati', 'routes/signUp.tsx', { id: 'it-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'it-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'it-album' }),
    route('profilo/:id', 'routes/publicProfile.tsx', { id: 'it-public-profile' }),
    route('profilo', 'routes/profile.tsx', { id: 'it-profile' }),
    route(ROUTES.it.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'it-privacy-policy' }),
  ]),
  ...prefix(ROUTES.pl.prefix, [
    index('routes/home.tsx', { id: 'pl-home-index' }),
    route('zaloguj-sie', 'routes/signIn.tsx', { id: 'pl-sign-in' }),
    route('zarejestruj-sie', 'routes/signUp.tsx', { id: 'pl-sign-up' }),
    route('albumy', 'routes/albums.tsx', { id: 'pl-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'pl-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'pl-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'pl-profile' }),
    route(ROUTES.pl.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'pl-privacy-policy' }),
  ]),
  ...prefix(ROUTES.nl.prefix, [
    index('routes/home.tsx', { id: 'nl-home-index' }),
    route('aanmelden', 'routes/signIn.tsx', { id: 'nl-sign-in' }),
    route('registreren', 'routes/signUp.tsx', { id: 'nl-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'nl-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'nl-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'nl-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'nl-profile' }),
    route(ROUTES.nl.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'nl-privacy-policy' }),
  ]),
  ...prefix(ROUTES.si.prefix, [
    index('routes/home.tsx', { id: 'si-home-index' }),
    route('prijava', 'routes/signIn.tsx', { id: 'si-sign-in' }),
    route('registracija', 'routes/signUp.tsx', { id: 'si-sign-up' }),
    route('albumi', 'routes/albums.tsx', { id: 'si-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'si-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'si-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'si-profile' }),
    route(ROUTES.si.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'si-privacy-policy' }),
  ]),
  ...prefix(ROUTES.fi.prefix, [
    index('routes/home.tsx', { id: 'fi-home-index' }),
    route('kirjaudu-sisaan', 'routes/signIn.tsx', { id: 'fi-sign-in' }),
    route('rekisteroidy', 'routes/signUp.tsx', { id: 'fi-sign-up' }),
    route('albumit', 'routes/albums.tsx', { id: 'fi-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'fi-album' }),
    route('profiili/:id', 'routes/publicProfile.tsx', { id: 'fi-public-profile' }),
    route('profiili', 'routes/profile.tsx', { id: 'fi-profile' }),
    route(ROUTES.fi.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'fi-privacy-policy' }),
  ]),
  ...prefix(ROUTES.se.prefix, [
    index('routes/home.tsx', { id: 'se-home-index' }),
    route('logga-in', 'routes/signIn.tsx', { id: 'se-sign-in' }),
    route('registrera', 'routes/signUp.tsx', { id: 'se-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'se-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'se-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'se-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'se-profile' }),
    route(ROUTES.se.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'se-privacy-policy' }),
  ]),
  ...prefix(ROUTES.no.prefix, [
    index('routes/home.tsx', { id: 'no-home-index' }),
    route('logg-inn', 'routes/signIn.tsx', { id: 'no-sign-in' }),
    route('registrer', 'routes/signUp.tsx', { id: 'no-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'no-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'no-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'no-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'no-profile' }),
    route(ROUTES.no.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'no-privacy-policy' }),
  ]),
  ...prefix(ROUTES.dk.prefix, [
    index('routes/home.tsx', { id: 'dk-home-index' }),
    route('log ind', 'routes/signIn.tsx', { id: 'dk-sign-in' }),
    route('registrer', 'routes/signUp.tsx', { id: 'dk-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'dk-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'dk-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'dk-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'dk-profile' }),
    route(ROUTES.dk.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'dk-privacy-policy' }),
  ]),
  ...prefix(ROUTES.hu.prefix, [
    index('routes/home.tsx', { id: 'hu-home-index' }),
    route('bejelentkezes', 'routes/signIn.tsx', { id: 'hu-sign-in' }),
    route('regisztracio', 'routes/signUp.tsx', { id: 'hu-sign-up' }),
    route('album', 'routes/albums.tsx', { id: 'hu-albums' }),
    route('album/:id', 'routes/album.tsx', { id: 'hu-album' }),
    route('profil/:id', 'routes/publicProfile.tsx', { id: 'hu-public-profile' }),
    route('profil', 'routes/profile.tsx', { id: 'hu-profile' }),
    route(ROUTES.hu.privacyPolicy, 'routes/privacyPolicy.tsx', { id: 'hu-privacy-policy' }),
  ]),
  route('album/:id', 'routes/album.tsx'),
  route('profil/:id', 'routes/publicProfile.tsx'),
  route(':path', 'routes/shortLink.tsx'),
] satisfies RouteConfig;
