name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        cd ./backend
        yarn install
    - name: Lint
      run: |
        cd ./backend
        yarn run lint
    - name: build
      run: |
        cd ./backend
        mv ./src/config.example.ts ./src/config.ts
        yarn run build
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        cd ./frontend
        yarn install
    - name: Lint
      run: |
        cd ./frontend
        yarn run lint
    - name: build
      run: |
        cd ./frontend
        mv ./src/config.example.ts ./src/config.ts
        CI=false yarn run build
